server:
  port: 8100
spring:
  application:
    name: spring-cloud-consumer
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true